### ISSUE TITLE
github action的schedule

### ISSUE THREAD

**Issue by Tomotoes** [Tomotoes/weibo#20]
突然想到了一点，`Github Action` 有多种监听类型，比如：push，pr，issue，comment，etc.
但最“实用”的是`schedule`触发：
```yaml
on:
  schedule:
    - cron: "*/30 * * * *"
```
我完全可以利用`schedule`当作一个免费的云函数啊。
比如：每天定时爬取xxx，发送到电报群，邮件这样的基本应用。
