### ISSUE TITLE
4.4

### ISSUE THREAD

**Issue by Tomotoes** [Tomotoes/weibo#51]
对抗击新冠肺炎疫情斗争牺牲的烈士和逝世同胞的深切哀悼，愿逝者安息，愿生者奋发。
```css
html { 
  -webkit-filter:grayscale(1) 
} 
```
